### PR TITLE
Docfix 4.1.0 cli reference

### PR DESCRIPTION
**Pull request by beatboxchad**
I've migrated the Import commands from the wiki Command Line Reference page.

Let me know if I'm off base on anything. One bit of ambiguous wording I noticed:

> ow - this option determines how resources with duplicate ResourceIDs will be handled. This option only applies to csv import. json import overwrites data. It will not modify existing data within a card or node.

What does "it" refer to? JSON import, or the -ow option?

Thanks!

### CODE REVIEW

**Comment by mradamcox** [comment]
@beatboxchad you're right, that is ambiguous. The intended message is that JSON import _always_ overwrites, and `append` is therefore not applicable in that situation. You can re-word as you like.

Overall the PR looks good. I'm noticing that the ES section is messed up (and was before, my fault). Could you add a commit that adds the "run" command (as you can find in this wiki page https://github.com/archesproject/arches/wiki/Installing-and-Running-Elasticsearch), and also updates the link to point to that wiki page? In a later PR we can migrate all that ElasticSearch stuff over to RTD, but that's not top priority now.

**Comment by mradamcox** [comment]
Once I merge this, I'll take care of `cherry-pick`ing the commit to the other relevant branches. I can do that locally can push straight to this repo.

**Comment by beatboxchad** [comment]
One last quick question. "It will not modify existing data within a card or node" -- does "It" refer to the 'overwrite' option to -ow?

**Comment by mradamcox** [comment]
Sorry about my reference to `append` above, I think that is actually just for importing resource models and branches not for business data (resources themselves). Hopefully @ryan can shed a little light.

**Comment by beatboxchad** [comment]
I'm actually sleuthing around in the code (arches/app/utils/data_management/resources/importer.py), and it looks like in my fork of master (that's LATEST, right?) it's indeed {'overwrite'|'append'}

I'm gonna update these docs accordingly, and yeah anything Ryan says will be taken into account.

**Comment by ryan86** [comment]
@beatboxchad the ow option applies to business data import, specifically the ow option applies to csv import of business data. There are two valid values for the ow option:

append - appends data to an existing resource when import encounters an resource with the same resourceid as a resource already in arches.

overwrite - overwrites an existing resource when import encounters a resource with the same resourceid as a resource already in arches.

I think that last sentence ("It will not modify existing data within a card or node" ) is in reference to a conversation I had with Adam Cox about overwriting/appending data to a specific node/nodegroup. I think what I was trying to express was that the ow option acts on the whole resource not just a part of it.

I hope this helps.

**Comment by beatboxchad** [comment]
Thanks man! It does indeed. Changes coming right up.

**Comment by mradamcox** [comment]
reworded the `ow` explanation to follow Ryan's explanation a little more closely. All good.

**Pull request merged**
