### PR TITLE
master <- Arches Apps

### PR DESCRIPTION
**Pull request by ekansa**
### brief description of changes
Added a section to the "Development" part of the documentation to introduce "Arches apps" as an architectural pattern for extending Arches.

#### issues addressed
Hopefully provided clear definitions of an Arches application / app, how they get used in projects, and their advantages for developing more experimental or specialized features.

#### further comments
We can update the link to @chiatt 's demo "Dashboard" app. We may also want to extend this to include more discussion about how one goes about developing custom apps, since this mainly discusses how to install an app. You can temporarily read the update at this link: https://arches.readthedocs.io/en/apps_m/developing/extending/creating-apps/

---

This box **must** be checked
- [X] the PR branch was originally made from the base branch

This box **should** be checked
- [X] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

### CODE REVIEW

**Review by chrabyrd — APPROVED** [review]
This lgtm!

**Review by mradamcox — APPROVED** [review]
Of course I'm well out of the loop here, but this looks great. It would be nice to have an example of creating an app from scratch, like `python manage.py startapp polls` or something, in addition to the pre-made dashboard app.

**Comment by ekansa** [comment]
Thanks @chrabyrd and @mradamcox ! I agree, it would be great to illustrate how to actually compose an app. My guess one would start with the "normal" approach one would take with Django?

https://docs.djangoproject.com/en/4.2/intro/tutorial01/#creating-the-polls-app

I'll add a reference to that.

**Comment by mradamcox** [comment]
Sounds good @ekansa. In the past I have used separate Django apps just like this to add new models and capabilities outside of the arches "project", so it's nice to see this paradigm being more thoroughly pursued.

**Pull request merged**
