### PR TITLE
Ydrea

### PR DESCRIPTION
**Pull request by ydrea**
### brief description of changes

I added some warnings, notes and links between chapters

#### further comments

Issues I ran into while cloning a 6.2.3 instance.

---

This box **must** be checked
- [*] the PR branch was originally made from the base branch

This box **should** be checked
- [*] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [*] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

### CODE REVIEW

**Comment by chiatt** [comment]
Hi @ydrea thanks for this PR. Given the large number of commits and files changed, I suspect you didn't make your changes to a fork of master. That's not a problem as long as we know what branch you used. Do you recall which one it was?

**Comment by ydrea** [comment]
yes, 6.2
that is the version I have been working on

**Comment by ekansa** [comment]
@ydrea I just returned from Europe so I'm sorry for the few days of lag in my response. 

I just modified your PR so that it would merge into the 6.2 branch of this repo (https://github.com/archesproject/arches-docs/tree/6.2). It'll make it much easier to review and incorporate your enhancement. 

@chiatt I see you commented here and were a suggested reviewer. But when I changed the base branch, it looks like my change removed the suggested reviewers! @ydrea if you could add suggested reviews again? 

Thanks for your patience!

**Comment by ekansa** [comment]
This PR inspired other updates (see comment thread), and should be closed.

**Pull request closed without merging**
