### PR TITLE
re #24 added map layer commands to command-line-reference.txt

### PR DESCRIPTION
**Pull request by beatboxchad**
Here's these! My editor cleaned up some whitespace, pardon the confusion.

### CODE REVIEW

**Comment by mradamcox** [comment]
@beatboxchad could you remake/edit this PR to put it into the 4.1.0 branch? I think that may solve the merge conflict that's showing up.

**Comment by beatboxchad** [comment]
4.1.0 had some conflicts; I was working from the 4.1.1 branch. Lemme rebase upstream changes and try again, one second.

**Comment by beatboxchad** [comment]
That's actually an obvious error -- was totally working from 4.1.0.

Anyway, we'd talked today in person about adding more information to this section, such as the command-line opts. So how bout I discard this, pull down the upstream to my fork, re-apply my changes with the extra stuff, and try this again? Go ahead and reject the merge and close it and I'll do the requisite git dance.

**Comment by mradamcox** [comment]
@beatboxchad That sounds good to me. Thanks!

**Pull request closed without merging**
