### PR TITLE
237 Added new Accessibility page and menu item

### PR DESCRIPTION
**Pull request by phudson-he**
### brief description of changes
Added new Accessibility page and menu item under "DEVELOPING WITH ARCHES"

---

This box **must** be checked
- [x] the PR branch was originally made from the base branch

This box **should** be checked
- [x] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

### CODE REVIEW

**Comment by mradamcox** [comment]
@phudson-he this looks great to me. For the sake of consistency with the rest of the docs though, would you mind adding a commit to change colour to color (6 occurrences), and practise to practice (1 occurrence)? I'll merge after that. Then we can have people look it over in /latest, and barring any issues I've missed, we can cherry-pick the commits all into the 5.1 branch to get this in /stable.

**Comment by phudson-he** [comment]
@mradamcox Changes done

**Comment by mradamcox** [comment]
Great. Will merge this now, and it will be live in the /latest docs. We can cherry-pick the commits into 5.1 after more people have a chance to look this new section over.

**Comment by phudson-he** [comment]
Thanks @mradamcox

**Pull request merged**
