### PR TITLE
Document the API endpoint for concepts RE #3399

### PR DESCRIPTION
**Pull request by jmunowitch**

### CODE REVIEW

**Comment by mradamcox** [comment]
@jmunowitch It looks like the parameters all still have filler values (test) but I figure this is in progress? Looks great overall.

**Comment by apeters** [comment]
@jmunowitch I would reduce the size of the example return by removing unnecessary duplication (for example, only have 1 sub concept in the return, and only have 1 value, etc...) 

Also your example request has an incorrect reference to `resource instance id`

**Comment by jmunowitch** [comment]
@mradamcox, @apeters: I have a new commit to address both of the issues you raise.

**Comment by apeters** [comment]
Looks good to me.  Go ahead and merge it.

**Pull request merged**
